export const BADGES = [
  {
    id: 'first-simulation',
    name: 'Primer Paso',
    description: 'Ejecuta tu primera simulación',
    icon: 'Play',
    color: 'text-green-400',
    rarity: 'common',
    xpBonus: 25,
    condition: (stats) => stats.simulationsRun >= 1,
  },
  {
    id: 'no-overshoot',
    name: 'Sin Sobreimpulso',
    description: 'Diseña un sistema con sobreimpulso menor al 2%',
    icon: 'TrendingDown',
    color: 'text-blue-400',
    rarity: 'rare',
    xpBonus: 75,
    condition: (stats) => stats.bestOvershoot !== null && stats.bestOvershoot < 2,
  },
  {
    id: 'five-challenges',
    name: 'Desafiante',
    description: 'Completa 5 retos',
    icon: 'Trophy',
    color: 'text-amber-400',
    rarity: 'rare',
    xpBonus: 100,
    condition: (stats) => stats.challengesCompleted >= 5,
  },
  {
    id: 'precise-control',
    name: 'Sintonizador Fino',
    description: 'Logra error en estado estacionario menor al 0.5%',
    icon: 'Target',
    color: 'text-cyan-400',
    rarity: 'epic',
    xpBonus: 150,
    condition: (stats) => stats.bestSteadyStateError !== null && stats.bestSteadyStateError < 0.5,
  },
  {
    id: 'all-modules',
    name: 'Explorador',
    description: 'Completa todos los módulos teóricos',
    icon: 'BookOpen',
    color: 'text-violet-400',
    rarity: 'epic',
    xpBonus: 200,
    condition: (stats) => stats.modulesCompleted >= 6,
  },
  {
    id: 'speed-runner',
    name: 'Tiempo Récord',
    description: 'Resuelve un reto en menos de 60 segundos',
    icon: 'Zap',
    color: 'text-yellow-400',
    rarity: 'rare',
    xpBonus: 100,
    condition: (stats) => stats.fastestChallenge !== null && stats.fastestChallenge < 60,
  },
  {
    id: 'master-pid',
    name: 'Maestro PID',
    description: 'Completa todos los retos de sintonización PID',
    icon: 'Award',
    color: 'text-red-400',
    rarity: 'legendary',
    xpBonus: 300,
    condition: (stats) => stats.pidChallengesCompleted >= 6,
  },
  {
    id: 'week-streak',
    name: 'Constancia',
    description: 'Usa la plataforma 7 días seguidos',
    icon: 'Flame',
    color: 'text-orange-400',
    rarity: 'rare',
    xpBonus: 100,
    condition: (stats) => stats.streakDays >= 7,
  },
]

export const RARITY_COLORS = {
  common: 'border-slate-500',
  rare: 'border-blue-500',
  epic: 'border-violet-500',
  legendary: 'border-amber-400',
}
